##
## EPITECH PROJECT, 2024
## B-CPE-200-NCE-2-1-amazed-florent.serra
## File description:
## Makefile
##

all:
		@make -C ./my
		@make -C ./lib_list

clean:
		@make clean -C ./my
		@make clean -C ./lib_list

fclean:
		@make fclean -C ./my
		@make fclean -C ./lib_list

re:
		@make re -C ./my
		@make re -C ./lib_list
